apiVersion: v1
kind: Service
metadata:
  labels:
    ai.clipper.container.label: ""
    ai.clipper.name: mgmt-frontend
  name: mgmt-frontend
spec:
  type: NodePort
  ports:
  - name: "1338"
    port: 1338
    targetPort: 1338
  - name: "1339"
    port: 1339
    targetPort: 1339
  selector:
    ai.clipper.name: mgmt-frontend
